### ISSUE TITLE
Main menu with options for "FIGHT" & "CUSTOMIZE"

### ISSUE THREAD

**Issue by jamesdaus** [dev-launchers/devbots__general#10]
Starts on main menu with button which leads to fighting scene, and one which leads to customization scene

**Comment by ECHO4BRAVO6** [comment]
![Screenshot 2021-06-19 141846](https://user-images.githubusercontent.com/71234983/122653307-612a3900-d109-11eb-8ac2-4784976cfacb.png)
From left to right order: Uplink/"Fight"/"Customize"/Settings/Credits
At the bottom is the exit button
