### ISSUE TITLE
Create ERC721 NFT contract draft

### ISSUE THREAD

**Issue by jamesdaus** [dev-launchers/devbots__general#3]
NFT Requirements
- Which slot the component fills (Paint, Move, Attack, Gadget, Face)
- Which particular part it is (ex. knife or laser?)
- Ability to be minted (to be further honed)

**Comment by Zorro909** [comment]
Might be worth looking into how ERC1155 works, to see if that makes sense for us, since we'll be having Bots, Parts and Instructions as distinct NFTs and ERC1155 seems to provide an easy way to put that into one smart contract.
